# Generated by Django 3.2.15 on 2023-03-27 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import holiday.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holiday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_date', models.DateField(blank=True, default=None, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('duration', models.CharField(choices=[(7, '7 Days'), (14, '14 Days'), (21, '21 Days')], default=7, max_length=10)),
                ('status', models.IntegerField(choices=[(0, 'Booking Made'), (1, 'Booking Confirmed')], default=0)),
                ('product_choice', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='product_list', to='holiday.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
    ]
