# Generated by Django 3.2.15 on 2023-04-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0003_auto_20230403_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
